name: Bug Report
description: File a bug report
title: "[BUG]: "
labels: bug
body:
  - type: textarea
    id: bug-description
    attributes:
      label: Description of the bug
    validations:
      required: true
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps To Reproduce
      placeholder: |
        1. Go to '...'
        2. Click on '...'
        3. Scroll down to '...'
        4. See error
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
