name: Feature Request
description: Request a new feature
title: "[FEAT]: "
labels: enhancement
body:
  - type: textarea
    id: feature-description
    attributes:
      label: Description of the feature
    validations:
      required: true
      
  - type: textarea
    id: additional-information
    attributes:
      label: Additional Information
