name: deploy
on:
  push:
    branches: [main]
defaults:
  run:
    working-directory: flashcard
jobs:
  build_and_deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - run: flutter analyze
      - run: flutter pub get
      - run: flutter test
      - run: flutter config --enable-web
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLASHCARD_6EDC2 }}'
          channelId: live
          projectId: flashcard-6edc2
          entryPoint: flashcard