name: preview url
on: [pull_request_target]
defaults:
  run:
    working-directory: flashcard
jobs:
  build_and_preview:
    if: ${{ github.actor != 'dependabot[bot]' }}
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.7.12'
          channel: 'stable'
      - run: flutter analyze
      - run: flutter pub get
      - run: flutter test
      - run: flutter config --enable-web
      - run: flutter build web --release
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_FLASHCARD_6EDC2 }}'
          projectId: flashcard-6edc2
          entryPoint: flashcard
          branch: ${{ github.event.pull_request.head.ref }}
